<?php $v=$old?:($problem??[]);$action=$problem?'/organizer/contests/'.$contest['contest_id'].'/problems/'.$problem['problem_id']:'/organizer/contests/'.$contest['contest_id'].'/problems';?>
<div class="section-head"><div><h2><?=$problem?'Edit problem':'Add problem'?></h2><p class="muted"><?=e($contest['contest_title'])?></p></div><a class="button-outline" href="<?=e(url('/contests/'.$contest['contest_id'].'/problems'))?>">Back</a></div>
<form class="card form-grid" method="post" action="<?=e(url($action))?>"><?=csrf_field()?>
<div class="field"><label for="code">Problem code</label><input id="code" name="code" maxlength="10" value="<?=e($v['code']??$v['problem_code']??'')?>" required></div><div class="field"><label for="title">Title</label><input id="title" name="title" value="<?=e($v['title']??$v['problem_title']??'')?>" required></div>
<div class="field field-full"><label for="statement">Statement</label><textarea id="statement" name="statement" required><?=e($v['statement']??$v['problem_statement']??'')?></textarea></div>
<div class="field"><label for="input_format">Input format</label><textarea id="input_format" name="input_format" required><?=e($v['input_format']??'')?></textarea></div><div class="field"><label for="output_format">Output format</label><textarea id="output_format" name="output_format" required><?=e($v['output_format']??'')?></textarea></div>
<div class="field field-full"><label for="constraints_text">Constraints</label><textarea id="constraints_text" name="constraints_text"><?=e($v['constraints_text']??'')?></textarea></div>
<div class="field"><label for="sample_input">Sample input</label><textarea id="sample_input" name="sample_input"><?=e($v['sample_input']??'')?></textarea></div><div class="field"><label for="sample_output">Sample output</label><textarea id="sample_output" name="sample_output"><?=e($v['sample_output']??'')?></textarea></div>
<div class="field"><label for="difficulty">Difficulty</label><select id="difficulty" name="difficulty"><?php foreach(['EASY','MEDIUM','HARD'] as $d):?><option <?=($v['difficulty']??'EASY')===$d?'selected':''?>><?=$d?></option><?php endforeach;?></select></div><div class="field"><label for="display_order">Display order</label><input id="display_order" name="display_order" type="number" min="1" value="<?=e($v['display_order']??1)?>"></div>
<div class="field"><label for="time_limit">Time limit (ms)</label><input id="time_limit" name="time_limit" type="number" min="1" value="<?=e($v['time_limit']??$v['time_limit_ms']??1000)?>"></div><div class="field"><label for="memory_limit">Memory limit (MB)</label><input id="memory_limit" name="memory_limit" type="number" min="1" value="<?=e($v['memory_limit']??$v['memory_limit_mb']??64)?>"></div>
<?php if($errors):?><div class="field-full field-error"><?=e(implode(' ',$errors))?></div><?php endif;?><div class="field-full actions"><button class="button">Save problem</button><a class="button-outline" href="<?=e(url('/contests/'.$contest['contest_id'].'/problems'))?>">Cancel</a></div></form>
