SET SERVEROUTPUT ON
BEGIN
    FOR r IN (SELECT object_name,object_type FROM user_objects WHERE object_name IN (
        'V_LEADERBOARD','V_CONTEST_STATUS','USER_PACK','PROBLEM_PACK','SP_REGISTER_PARTICIPANT','SP_ADD_ANNOUNCEMENT','SP_ANSWER_CLARIFICATION','FN_USER_SUBMISSION_COUNT','FN_CONTEST_PROBLEM_COUNT','TRG_PARTICIPANT_RATING_CHANGE','TRG_NEW_SUBMISSION_ROW','TRG_SUBMISSION_STATEMENT','TRG_CONTEST_STATUS_STATEMENT',
        'AUDIT_LOG','PASSWORD_RESET_TOKEN','CLARIFICATION','ANNOUNCEMENT','SUBMISSION','TEST_CASE','PROBLEM','CONTEST_REGISTRATION','CONTEST','USER_ROLE','APP_USER','ROLE',
        'SEQ_AUDIT_LOG','SEQ_PASSWORD_RESET','SEQ_CLARIFICATION','SEQ_ANNOUNCEMENT','SEQ_SUBMISSION','SEQ_TEST_CASE','SEQ_PROBLEM','SEQ_REGISTRATION','SEQ_CONTEST','SEQ_APP_USER'
    ) ORDER BY CASE object_type WHEN 'VIEW' THEN 1 WHEN 'TRIGGER' THEN 2 WHEN 'PACKAGE BODY' THEN 3 WHEN 'PACKAGE' THEN 4 WHEN 'PROCEDURE' THEN 5 WHEN 'FUNCTION' THEN 6 WHEN 'TABLE' THEN 7 WHEN 'SEQUENCE' THEN 8 ELSE 9 END) LOOP
        BEGIN
            IF r.object_type='TABLE' THEN EXECUTE IMMEDIATE 'DROP TABLE '||r.object_name||' CASCADE CONSTRAINTS PURGE';
            ELSIF r.object_type <> 'PACKAGE BODY' THEN EXECUTE IMMEDIATE 'DROP '||r.object_type||' '||r.object_name;
            END IF;
        EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Could not drop '||r.object_type||' '||r.object_name||': '||SQLERRM); END;
    END LOOP;
END;
/
PROMPT PCMS project objects removed

